module.exports = {
  lancamentos: require('./filmes/lancamentos'),
  filmes_hd: require('./filmes/filmes-hd'),
  acao: require('./filmes/acao'),
  antigos: require('./filmes/antigos'),
  animacao: require('./filmes/animacao'),
  aventura: require('./filmes/aventura'),
  comedia: require('./filmes/comedia'),
  c_romantica: require('./filmes/c-romantica'),
  corrida: require('./filmes/corrida'),
  crime: require('./filmes/crime'),
  documentario: require('./filmes/documentario'),
  drama: require('./filmes/drama'),
  faroeste: require('./filmes/faroeste'),
  ficcao: require('./filmes/ficcao'),
  guerra: require('./filmes/guerra'),
  musical: require('./filmes/musical'),
  nacional: require('./filmes/nacional'),
  policial: require('./filmes/policial'),
  religioso: require('./filmes/religioso'),
  romance: require('./filmes/romance'),
  suspense: require('./filmes/suspense'),
  terror: require('./filmes/terror'),
  thriller: require('./filmes/thriller')
}
